Added index, completion and references for table names, column names …
magento/magento2-phpstorm-plugin pull request #351
Opened 2020-10-24 10:20 UTC by bohdan-harniuk

**Description (*)**
This PR adds indexes, completion, references, test coverage on completion and references on table and column names in the db_schema.xml file.

![image](https://user-images.githubusercontent.com/31848341/97079209-b9e91680-15fa-11eb-81b7-4b2d1f19b222.png)
![image](https://user-images.githubusercontent.com/31848341/97079210-be153400-15fa-11eb-9f92-56e6480dcde1.png)
![image](https://user-images.githubusercontent.com/31848341/97079213-c3727e80-15fa-11eb-8e23-52e458e25783.png)

**Also, was changed the assertHasReferenceToXmlTag method of the BaseReferenceTestCase class to work with PolyVariantReferenceBase type that retrieves multiple references.**
![image](https://user-images.githubusercontent.com/31848341/97079226-ea30b500-15fa-11eb-90b4-7097183a54ab.png)

**After that change all tests passed successfully:**
![image](https://user-images.githubusercontent.com/31848341/97079332-ad18f280-15fb-11eb-89ff-9b7063cd2965.png)

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2020-10-25 18:00 UTC, VitaliyBoyko requested changes

2020-10-25 19:11 UTC, bohdan-harniuk commented on src/com/magento/idea/magento2plugin/indexes/IndexManager.java
> +            TableAndColumnNameIndex.KEY,
Done

2020-10-26 19:25 UTC, VitaliyBoyko requested changes
![image](https://user-images.githubusercontent.com/20116393/97218648-9e843400-17d1-11eb-8e85-fb0ac09c2fab.png)
An element should not have a reference to itself ⛔

2020-10-27 16:31 UTC, bohdan-harniuk commented
Fixed "An element should not have a reference to itself".

2020-10-28 17:33 UTC, VitaliyBoyko approved these changes
QA passed ✅ 
![image](https://user-images.githubusercontent.com/20116393/97474145-740eb400-1954-11eb-997a-8559e07b64c9.png)
![image](https://user-images.githubusercontent.com/20116393/97474154-77a23b00-1954-11eb-8efa-e6c19e8c170c.png)

2020-10-28 17:39 UTC, merged