Fixed model generation with same names
magento/magento2-phpstorm-plugin pull request #438
Opened 2020-12-22 10:27 UTC by drpayyne

**Description**

Fixed generation of models with same model/resource model name.

**Fixed Issues**

1. Fixes magento/magento2-phpstorm-plugin#437: The added model and collection classes contain duplicate names of the imported classes

**Contribution checklist**
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with integration/functional tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

2020-12-22 14:17 UTC, eduard13 requested changes
Thank you for the fix, could you please check my comments below?

2020-12-22 14:17 UTC, eduard13 commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
> +            resorceModelName = "ResourceModel";
Typo here
```suggestion
            resourceModelName = "ResourceModel";
```

2020-12-22 14:17 UTC, eduard13 commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
> +            resourceModelFqn.append(" as ResourceModel");
Can we extract the `ResourceModel` into a const and reuse it in all places we use it?

2020-12-22 14:17 UTC, eduard13 commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
> +        String resorceModelName = getResourceModelName();
```suggestion
        String resourceModelName = getResourceModelName();
```

2020-12-22 14:17 UTC, eduard13 commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
> +            resorceModelName = "ResourceModel";
```suggestion
            resourceModelName = "ResourceModel";
```

2020-12-22 14:17 UTC, eduard13 commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
> +            resorceModelName,
```suggestion
            resourceModelName,
```

2020-12-22 14:17 UTC, eduard13 commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewModelsDialog.java
> +        String resorceModelName = getResourceModelName();
```suggestion
        String resourceModelName = getResourceModelName();
```

2020-12-23 05:13 UTC, drpayyne commented
Hi @eduard13, thanks for catching my typos! I've implemented your suggested changes. Please review again.

2020-12-23 15:12 UTC, eduard13 approved these changes
Good job 👍

2020-12-23 15:50 UTC, merged