Fixed bug invalid check setup_version
magento/magento2-phpstorm-plugin pull request #504
Opened 2021-03-10 12:13 UTC by anzin

**Description** (*)
I've fixed the bug invalid check 'setup_version'.

![image](https://user-images.githubusercontent.com/30952336/110627511-bf5e8c00-81aa-11eb-9cd3-92767ea94b17.png)

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-10 12:16 UTC, VitaliyBoyko requested changes

2021-03-10 12:16 UTC, VitaliyBoyko commented on src/com/magento/idea/magento2plugin/inspections/xml/ModuleDeclarationInModuleXmlInspection.java
> +    private static final String MODULE_NAME = "name";
add this constant to `com.magento.idea.magento2plugin.magento.files.ModuleXml`
And write a test please. Thank you!

2021-03-11 10:31 UTC, anzin commented
@VitaliyBoyko I've fixed code by recommendation, and added test.

2021-03-11 11:17 UTC, VitaliyBoyko approved these changes

2021-03-11 11:17 UTC, merged