Web Api interface generation
magento/magento2-phpstorm-plugin pull request #586
Opened 2021-05-03 10:52 UTC by bohdan-harniuk

**Description** (*)
This PR adds the generation of a Web API interface for a service.

**What was done:**

1. generation of a Web API interface for a service.
2. added possibility to choose one or more methods to be included in an interface
3. added possibility to choose interface name and change its description (default one is taken from the service)
4. all methods short description taken from the service methods (or default TODO, that asks to add short description)
5. implements added for a service
6. implements class imported in use block for a service
7. all included in interface methods annotations replaced with @inheritDoc annotations.
8. added test case to test simple service with primitive types
9. added test case to test simple service with Object types
10. testing for inserting @inheritDoc annotations
11. testing for an interface implemented by a service
12. testing for interface FQN added in an import (use) block

**Service to add Web Api interface:**
<img width="888" alt="Screenshot 2021-05-03 at 13 45 47" src="https://user-images.githubusercontent.com/31848341/116867439-df905180-ac15-11eb-8a94-ebd3940fc6be.png">

**Open the context menu on it and choose Web API interface generation action:**
<img width="888" alt="Screenshot 2021-05-03 at 13 47 31" src="https://user-images.githubusercontent.com/31848341/116867555-1cf4df00-ac16-11eb-9a85-d17554399457.png">

**Choose methods to include in the interface, change default name and description:**
<img width="888" alt="Screenshot 2021-05-03 at 13 48 17" src="https://user-images.githubusercontent.com/31848341/116867675-3a29ad80-ac16-11eb-9156-4c67dde877f4.png">
<img width="888" alt="Screenshot 2021-05-03 at 13 48 56" src="https://user-images.githubusercontent.com/31848341/116867753-51689b00-ac16-11eb-8169-4ff930224247.png">

**Results:**
<img width="960" alt="Screenshot 2021-05-03 at 13 49 25" src="https://user-images.githubusercontent.com/31848341/116867811-61807a80-ac16-11eb-87d1-45a37858f445.png">
<img width="960" alt="Screenshot 2021-05-03 at 13 50 09" src="https://user-images.githubusercontent.com/31848341/116867901-7b21c200-ac16-11eb-8702-873c2e885810.png">
<img width="960" alt="Screenshot 2021-05-03 at 13 51 37" src="https://user-images.githubusercontent.com/31848341/116868020-b15f4180-ac16-11eb-869c-c8ef1d3a6154.png">

**Questions or comments**
To get generated Doc Annotations beautiful, go to the `Preferences... > Editor > Code Style > PHP > PHPDoc > Blank lines around parameters` and activate this configuration.

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-05-04 13:17 UTC, eduard13 requested changes
Hi @bohdan-harniuk, thank you for your contribution. Could you please rename all the visible text occurrences of `Api` to `API`, since [API](https://en.wikipedia.org/wiki/API) is an acronym and should be correctly used. Below you may see couple of places, but would be good to change it on every place that is visible to the user.

Also, can we exclude these API generators for `Test/` or probably `*Test.php` files, in order to not overload the context menu? I don't see any use case, when we have to create an API for any kind of tests.

Thank you.

2021-05-05 07:46 UTC, bohdan-harniuk commented on resources/META-INF/plugin.xml
> +        <internalFileTemplate name="Web Api Interface"/>
Done.

2021-05-05 07:46 UTC, bohdan-harniuk commented on src/com/magento/idea/magento2plugin/actions/generation/dialog/NewInterfaceForServiceDialog.form
> +              <text value="Api For Class"/>
Done.

2021-05-05 07:57 UTC, bohdan-harniuk commented
Thank you, @eduard13, for the great findings! I've fixed them.

<img width="1228" alt="Screenshot 2021-05-05 at 10 57 38" src="https://user-images.githubusercontent.com/31848341/117111737-b811c400-ad90-11eb-8a25-7098e432d649.png">

2021-05-05 09:08 UTC, eduard13 approved these changes
Thank you for your contribution 👍

2021-05-05 09:09 UTC, merged