963: Bug during composer json generation
magento/magento2-phpstorm-plugin pull request #972
Opened 2022-02-09 20:06 UTC by Iamwade

1. Fixes magento/magento2-phpstorm-plugin#963

2022-02-10 06:44 UTC, bohdan-harniuk requested changes
Hello, @Iamwade!

Please, check my suggestions.

2022-02-10 06:44 UTC, bohdan-harniuk commented on src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
>                      final JSONObject jsonObject = (JSONObject) obj;
jsonObject can be null as well.

2022-02-10 06:44 UTC, bohdan-harniuk commented on src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
>                      final String nameJsonElement = jsonObject.get("name").toString();
jsonObject.get("name") can be null as well.

2022-02-10 06:44 UTC, bohdan-harniuk commented on src/com/magento/idea/magento2plugin/actions/generation/generator/ModuleComposerJsonGenerator.java
> +                    final int minorVersionSeparator = version.lastIndexOf('.');
We should not do this if there is no version specified.

2022-02-10 20:09 UTC, bohdan-harniuk approved these changes
Hello, @Iamwade!

Looks better than before!
Thank you for your work here!

@eduard13, what do you think?

Regards,

2022-02-11 09:01 UTC, eduard13 approved these changes
Looks good 👍

2022-02-11 09:02 UTC, merged